services:
  app-chisso:
    container_name: app-chisso
    build: .
    command: nodemon app.js --watch . --ext js,json
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env
    depends_on:
      - mysql-db-chisso

  mysql-db-chisso:
    container_name: mysql-db-chisso
    image: mysql:8.0    
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    env_file:
      - ./app/.env

volumes:
  db_data:
